# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodityName', models.CharField(help_text='Enter name of commodity', max_length=50)),
                ('exporterName', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantityAvailable', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
