# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20181116_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commodityName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='exporterName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
