# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-18 10:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20181118_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='exporterName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
