# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-22 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20181118_1059'),
        ('trade', '0006_auto_20181118_1630'),
    ]

    operations = [
    ]
