# Generated by Django 2.1.3 on 2018-11-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='importerName',
            field=models.CharField(default='trader1', max_length=50),
        ),
    ]
