# Generated by Django 2.1.3 on 2018-11-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_request_importername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='importerName',
            field=models.CharField(max_length=50),
        ),
    ]
