# Generated by Django 2.1.3 on 2018-11-24 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_auto_20181124_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='importerName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
