# Generated by Django 2.1.3 on 2018-11-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_auto_20181124_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='exporterName',
            field=models.CharField(max_length=50),
        ),
    ]
